application: ft-tps-screener #System code of the app
environment: crm-prod-eu-west-1  # This should already exist under environments of the ip-crm-hako-config repo

stacks:
  web:
    type: public-load-balanced-web-service
    parameters:
      TaskCount: 1
      TaskCpu: 256
      TaskCpuArchitecture: ARM64
      TaskMemory: 512
      ContainerRegistry: docker.packages.ft.com/ip-container-registry
      ContainerRegistryCredentialsSecretName: /hako/registry-credential/cloudsmith/crm-en-full-stack-read-only
      ContainerGoodToGoEndpoint: /__gtg
      CustomDomainName: tps-screener.ft.com
      CustomDomainCertificateArn: arn:aws:acm:eu-west-1:615638662720:certificate/34132e9f-3be6-48b8-a085-9beb931d8dc4
      LogDestination: splunk 
      TaskPolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AccessProdDynamoDBTables"
            Effect: "Allow"
            Action:
              - "dynamodb:GetItem"
              - "dynamodb:PutItem"
              - "dynamodb:UpdateItem"
              - "dynamodb:DeleteItem"
              - "dynamodb:Query"
              - "dynamodb:Scan"
              - "dynamodb:DescribeTable"
              - "dynamodb:ListTables"
            Resource:
              - arn:aws:dynamodb:eu-west-1:027104099916:table/ft-email_platform_tps_lookup*
              - arn:aws:dynamodb:eu-west-1:615638662720:table/ft-tps-screener-prod
          - Sid: "AccessProdS3Buckets"
            Effect: "Allow"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:ListBucket"
            Resource:
              - arn:aws:s3:::email-platform-ftcom-tps 
              - arn:aws:s3:::email-platform-ftcom-tps/*
              - arn:aws:s3:::ft-tps-screener-prod
              - arn:aws:s3:::ft-tps-screener-prod/*

  scheduled-task:
    type: scheduled-task
    parameters:
      TaskCpuArchitecture: ARM64
      ContainerRegistry: docker.packages.ft.com/ip-container-registry
      ContainerRegistryCredentialsSecretName: /hako/registry-credential/cloudsmith/crm-en-full-stack-read-only
      TaskCpu: 256
      TaskMemory: 512
      TaskSchedule: "daily at 13:30"
      ContainerCommand: npm run update
      LogDestination: splunk
      TaskPolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AccessProdDynamoDBTables"
            Effect: "Allow"
            Action:
              - "dynamodb:GetItem"
              - "dynamodb:Query"
              - "dynamodb:Scan"
              - "dynamodb:ListTables"
              - "dynamodb:DescribeTable"
              - "dynamodb:PutItem"
              - "dynamodb:UpdateItem"
              - "dynamodb:DeleteItem"
            Resource:
              - arn:aws:dynamodb:eu-west-1:027104099916:table/ft-email_platform_tps_lookup*
              - arn:aws:dynamodb:eu-west-1:615638662720:table/ft-tps-screener-prod
          - Sid: "AccessProdS3Buckets"
            Effect: "Allow"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:ListBucket"
            Resource:
              - arn:aws:s3:::email-platform-ftcom-tps 
              - arn:aws:s3:::email-platform-ftcom-tps/*
              - arn:aws:s3:::ft-tps-screener-prod
              - arn:aws:s3:::ft-tps-screener-prod/*

  circleci-deployment-role:
    type: circleci-deployment-role
    parameters:
      CircleciProjectId: c9d89113-1fb3-43c5-869c-ad0b8eacf9d2 
      CircleciOrgName: Financial-Times


tags:
  systemCode: ft-tps-screener
  environment: p
